# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Setup locale
      run: |
        sudo locale-gen fr_FR.UTF-8
        sudo update-locale
        export LANG=fr_FR.utf8
        export JAVA_TOOL_OPTIONS="-Duser.language=fr -Duser.region=FR"
        export _JAVA_OPTIONS="-Duser.language=fr -Duser.region=FR"
        export JAVA_ARGS="-Duser.language=fr -Duser.region=FR"
        locale
    - name: Build
      run: gradle build
